name: Blutter Pro Engine Bot

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  workflow_dispatch:      # Manual trigger

concurrency:
  group: blutter-pro-bot
  cancel-in-progress: true

jobs:
  engine-run:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential pkg-config libicu-dev libcapstone-dev libfmt-dev
          pip install pyTelegramBotAPI requests pyelftools pymongo[srv] dnspython

      - name: Run Blutter Pro Bot
        env:
          LOG_CHANNEL: "@BotControlPanel" # এখানে আপনার লগ চ্যানেলের ইউজারনেম দিন
        run: python main.py
